[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
node-version = "20"

[nixpacks.build.env]
NPM_CONFIG_PRODUCTION = "false"

[env]
NODE_ENV = "production"
PORT = "5000"

[deploy.envs]
NODE_ENV = "production"
PORT = "5000"